baseURL: https://loisel.github.io/
languageCode: en-us
title: Dr. Alois Dirnaichner
theme: "hugo-alageek-theme"
markup:
  goldmark:
    renderer:
      unsafe: true
menus:
  primary:
    -
      weight: 3
      name: RESUME
      url: "/cv.pdf"
    -
      weight: 4
      name: MY WORK
      url: "./projects"
    -
      weight: 5
      name: HIRE
      url: "mailto:alois@dirnaichner.eu"

params:
  email: "alois@dirnaichner.eu"
  linkedin: "dirnaichner"
  github: "loisel"
  gitlab: "loisl"
  logofile: "/me2.jpg"
  latestprojectcount: 4
  latestpostcount: 4
  projects_navigation: true
