baseURL: http://example.org/
languageCode: en-us
title: DR. ALOIS DIRNAICHNER
theme: "hugo-alageek-theme"
markup:
  goldmark:
    renderer:
      unsafe: true
menus:
  primary:
    -
      weight: 3
      name: RESUME
      url: "/cv.pdf"
    -
      weight: 4
      name: MY WORK
      url: "./projects"
    -
      weight: 5
      name: HIRE

params:
  email: "alois@dirnaichner.eu"
  linkedin: "dirnaichner"
  logofile: "/me2.jpg"
  latestprojectcount: 4
  latestpostcount: 4
  projects_navigation: true
