baseURL: http://example.org/
languageCode: en-us
title: DR. ALOIS DIRNAICHNER
theme: "hugo-alageek-theme"
markup:
  goldmark:
    renderer:
      unsafe: true
menus:
  primary:
    -
      weight: 3
      name: RESUME
    -
      weight: 4
      name: MY WORK
    -
      weight: 5
      name: HIRE

params:
  logofile: "/me2.jpg"
